### ISSUE TITLE
[Feature Request] : 3 in total

### ISSUE THREAD

**Issue by zenny** [RaphGL/NeoSent#5]
Hi @RaphGL 

Three features as of below are very much expected:

1. Font size option (fixed) as in https://github.com/visit1985/mdp
2. the break feature as in https://github.com/visit1985/mdp/blob/2bd97c241af2741793941c2fc53c9d575b287cd3/sample.md?plain=1#L221-L242
3. PDF export (g in sent) or anything like https://github.com/hamptonmoore/sent-export

Thanks again.

**Comment by RaphGL** [comment]
hi again, 

From the ones you've listed, PDF exporting is/was a planned feature but I haven't gotten around to implementing it as I'd have to learn cairo and it wasn't that important to me at the time. 

As for the other two you said, neosent was a rewrite of sent which itself didn't have either of those features as it followed a minimalist approach to slideshows (based on a japanese practice).
I can consider implementing PDF later but for a more feature complete slideshow program in the same vain as this one I recommend [slides](https://sr.ht/~renerocksai/slides/)
which is already much more feature complete. 
I've thought about adding markdown support instead of the custom language used in the original so users could have much more freedom in how they format stuff but I just haven't felt the need for it (I don't do presentations often anymore)
